USE FRUX;
ALTER TABLE `生産タスク` ADD COLUMN `手動数` INT NOT NULL DEFAULT 0;
ALTER TABLE `生産タスク` ADD COLUMN `自動数` INT NOT NULL DEFAULT 0;
ALTER TABLE `生産タスク` 
    ADD COLUMN `予定開始時刻` DATETIME NULL,
    ADD COLUMN `予定通過時刻` DATETIME NULL;
    ADD COLUMN `開始時刻` DATETIME NULL;
    ADD COLUMN `終了時刻` DATETIME NULL;

SELECT * FROM 生産タスク LIMIT 2;



